<div class="container">
	<div class="grid grid-cols-11 gap-2">
		<div class="bg-gray-700 text-white">GO</div>
		<div class="bg-blue-500 text-white">Mediterranean Avenue</div>
		<div class="bg-gray-400" />
		<div class="bg-blue-500 text-white">Baltic Avenue</div>
		<div class="bg-gray-400" />
		<div class="bg-red-500 text-white">Reading Railroad</div>
		<div class="bg-gray-400" />
		<div class="bg-yellow-500 text-white">Oriental Avenue</div>
		<div class="bg-gray-400" />
		<div class="bg-yellow-500 text-white">Vermont Avenue</div>
		<div class="bg-gray-400" />
		<div class="bg-yellow-500 text-white">Connecticut Avenue</div>
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-yellow-500 text-white">Connecticut Avenue</div>

    <div class="bg-yellow-500 text-white">Connecticut Avenue</div>
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-yellow-500 text-white">Connecticut Avenue</div>

    <div class="bg-yellow-500 text-white">Connecticut Avenue</div>
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-white" />
		<div class="bg-yellow-500 text-white">Connecticut Avenue</div>
		
    <div class="bg-gray-700 text-white">GO</div>
		<div class="bg-blue-500 text-white">Mediterranean Avenue</div>
		<div class="bg-gray-400" />
		<div class="bg-blue-500 text-white">Baltic Avenue</div>
		<div class="bg-gray-400" />
		<div class="bg-red-500 text-white">Reading Railroad</div>
		<div class="bg-gray-400" />
		<div class="bg-yellow-500 text-white">Oriental Avenue</div>
		<div class="bg-gray-400" />
		<div class="bg-yellow-500 text-white">Vermont Avenue</div>
		<div class="bg-gray-400" />
	</div>
</div>